### ISSUE TITLE
[v2] steps as keyed objects

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/installer-configs#17]
For v2, we might thing about implementing steps as keyed objects, eg:

```yml
    steps:
      - adb:reboot:
          to_state: "bootloader"
        fallback:
          - user_action:
              action: "bootloader"
        condition:
          var: "bootstrap"
          value: true
      - fastboot:reboot_bootloader:
      - fastboot:set_active:
          slot: "b"
```

Might make schema validation and documentation easier.
