### ISSUE TITLE
Provide a way to add line breaks to user actions

### ISSUE THREAD

**Issue by amartinz** [ubports/installer-configs#185]
To improve readability, it would be nice to have support for line breaks in user actions, for example:

```
  fastbootd:
    title: "Reboot to Fastbootd"
    description: "With the device powered off, hold Volume Down + Power to boot into recovery.<br><br>Inside the recovery, press on 'Advanced' and select 'Enter fastboot'."
    image: "phone_power_down"
    button: true
```
`<br>` does not get handled and is rendered in text.
`\n` does not get handled and removed from text.

![image](https://user-images.githubusercontent.com/2779871/160370525-2b65df4a-3dec-4bdc-adfb-e81758a4f244.png)
