### ISSUE TITLE
[v3] option interdependencies

### ISSUE THREAD

**Issue by NeoTheThird** [ubports/installer-configs#87]
It should be possible to only display certain options if other options are met. A possible structure could be:

```
options:
      - var: "opengapps"
        name: "Install OpenGapps"
        type: "boolean"
        value: false
      - var: "opengappsChannel"
        name: "OpenGapps Channel"
        tooltip: "Do you want to install pico nano micro mini full version of OpenGapps?"
        link: "https://opengapps.org/"
        type: "select"
        remote_values:
          opengapps:channels:
        condition:
          var: "opengapps"
          value: true
```

_Originally posted by @Vince1171 in https://github.com/ubports/installer-configs/issues/86#issuecomment-792809887_

Usecases:
- #86
- https://gitlab.com/postmarketOS/postmarketos/-/issues/38
